### ISSUE TITLE
property / value alignment

### ISSUE THREAD

**Issue by travisghansen** [vinteo/py-opensprinkler#16]
@vinteo do you think we should rename a few things...

controller.operation_enabled to controller.enabled
and then the various `_name` properties of `station` and `program` should return `_` instead of `-` values?

**Comment by vinteo** [comment]
I agree with the controller. Where are we using `-`?

**Comment by vinteo** [comment]
Oh sorry for some reason I thought this was `hass-opensprinkler`. I don't have a strong preference either way with `_` or `-` as long as it consistent. But I probably lean more to `-` for values

**Comment by vinteo** [comment]
Let's make it underscore then

**Comment by travisghansen** [comment]
Ok.
