### ISSUE TITLE
Add support to run once off program

### ISSUE THREAD

**Issue by vinteo** [vinteo/py-opensprinkler#22]
`/cr?t=[X,X,X,X,...]` endpoint where C is number of seconds

**Comment by travisghansen** [comment]
@vinteo want me to add a specific method for this? Or just use the generic `.request()` method?

**Comment by vinteo** [comment]
should be a method on the controller that accepts an array?

**Comment by travisghansen** [comment]
@vinteo k, I'll knock it out.
