### ISSUE TITLE
Thoughts on PR22

### ISSUE THREAD

**Issue by PeteBa** [vinteo/py-opensprinkler#24]
A few thoughts on the latest PR #22 (apologies as I see it has been merged):

- Should string literals returned to downstream code be declared constants that can be imported by downstream code, e.g. `reboot_reason`, `sensor_type`, `hardware_type` all return hardcoded strings.

- Is there value in providing both `hardware_type` and `hardware_type_name` routines as they are the same information just in different formats. I would suggest refactor to have `hardware_type` return a string constant and to avoid exposing internals like "172" and "220". Similar for sensor type and name.

- Is there value in providing `flow_count_window` and `flow_count` given `flow_rate` is provided ? It may just introduce latter problems to downstream code if the library OS api changes. I think there might be value in holding back on exposing some OS internals.

- Should Sensors be abstracted from the OS API and be a bit more like Stations. i.e. return an array of sensor objects with properties including `name`, `type`, `enabled`, `state`, ... This might also make it easier to discover/create the equivalent sensors in the HA integration.

- A thought that you could combine master on/off adjustment into a single `master_1_time_adjustment` routine that returns {"on_delay": x, "off_delay": y}. Similarly with `longitude` and `latitude`

- For routines that return `timestamps` or `IP  Addressees`, is there value in using standard types such as `datetime` and `ipaddress`

- Should there be a guard clause on the various `ip`, `gw`, `dns` routines to test for `dhcp` active otherwise return None

Please consider the above as just "quick thoughts" as I dont pretend to be very familiar with the library and the decisions to date. Just trying to be helpful.

**Comment by travisghansen** [comment]
@PeteBa yeah good stuff. I suppose much of the decision has been driven by:

- focused on the `hass` use-case
- velocity

I like the constant idea...was thinking about that before but was going so fast I didn't implement it.

`{type,type_name}` situations are mostly driven by:

- wanting to expose the real value in `hass` for automations...which using the real value for the various 'set' methods is driven by being lazy and not wanting to code out the mappings to handle both real values and translated values
- wanting to expose something readable as `state attributes`

Not sure on the flow properties...there were there so I added them.

The sensors is an interesting idea I hadn't considered. I'm inclined to leave them as is to mimic the API's handling a little more closely. If they ever do implement as a list/array I think we should change.

The time adjustments, lat/long, etc are really done the way they are to simplify how `hass` consumes these (`state attributes`). It may make sense to alter how they behave here and put more logic in the integration.

I think using the standard types is a great idea especially if they 'toString' into something sane. Again driven by the `hass` use-case of simply adding these as `state attributes`.

The IPs can be more defensive for sure. I don't think it makes sense to put them behind `dhcp` though right? I can have all those attributes (gw/dns/ntp/etc) even if `dhcp` is off.

Thanks for the input! Contributions welcome as well. I'm mostly burning really fast just to get the `hass` integration done :)

**Comment by vinteo** [comment]
This library was created for the purpose of using it for the HA integration. So really it was meant to expose the information and functions needed for this integration, to start off with anyway. So I agree with a lot of your points about exposing all the attributes, but it was low impact so it didn't really bother me. 

The constants stuff will definitely be a very nice cleanup as well and we should definitely do it, but currently the integration does not need it as really we are just exposing the info to the HA user, whether it is a sensor or attribute. There is hardly any logic there so HA does not need import the constants.

The "sensors" stuff looks like a good idea, could be an improvement we look at in the future.

So with the better representation of some of the data (ip, loc, etc), it is not really needed at the moment, in fact I doubt it will be used much in HA. I was never planning on adding them. Perhaps this library will be used by others for other things so we will consider it when the time comes and it is requested. 

Having said that, contributions are ALWAYS very welcome :)

**Comment by PeteBa** [comment]
Closing as more questions than issues. My original intent was to couple this with influxdb library for logging and monitoring via grafana. Instead will try the same via my HA installation. Appreciate the insight into the library and purpose as well as taking contributions.
