### ISSUE TITLE
use http keep-alive

### ISSUE THREAD

**Issue by travisghansen** [vinteo/py-opensprinkler#34]
https://httplib2.readthedocs.io/en/latest/libhttplib2.html#

```
headers={"Connection":" keep-alive"})
```

This may help with struggling hardware?

**Comment by vinteo** [comment]
I did try this a while back when I was trying to optimise the calls, it didn't make a difference for my hardware so I don't see any harm in trying this

**Comment by travisghansen** [comment]
I'm testing it out locally to see if it makes any difference for me. I do have a load balancer in front but I'd assume the load balancer is behaving in the same fashion but maybe not..we'll see what happens.

If not, we'll need to fall back more agressively or I'll need to wire things up in `Node-RED` to issue a reboot when it stops responding to the `/ja` endpoint.

**Comment by vinteo** [comment]
this has gone in with #37
