### ISSUE TITLE
pyopensprinkler won't work with Home Assistant 2022.11.x

### ISSUE THREAD

**Issue by Bascht74** [vinteo/py-opensprinkler#67]
I get the following log output after installing HA 2022.11.b0:
```
2022-10-27 10:10:28.603 ERROR (SyncWorker_7) [homeassistant.util.package] Unable to install package pyopensprinkler==0.7.3: ERROR: Cannot install pyopensprinkler==0.7.3 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2022-10-27 10:10:28.604 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration opensprinkler: Requirements for opensprinkler not found: ['pyopensprinkler==0.7.3'].
```

Next week it wil fail for everyone installing the update.

Could you please address the dependencies conflict? Thx!

Sebastian Lotz

**Comment by vinteo** [comment]
I am having trouble trying to figure our the conflicts... `aiohttp` seems to be the same version unless I am misunderstanding this.

And for some reason my lcaol environment for home assistant is failing now. I will try again with a fresh install of Ubuntu.

**Comment by vinteo** [comment]
Update:

I managed to reproduce your error, but I am struggling to see a cause or a fix. Do you have any idea? If I install the dependency manually using `pip` it works fine.

**Comment by Bascht74** [comment]
No, I don't.

I looked around in discord to find a place where to discuss this but I was not successful so far. 
Maybe you could ask in the beta forum becaus you said that it installs OK manually.
https://discord.com/channels/330944238910963714/427516175237382144

Could you share the command how you installed it manually? 
(e.g. with docker exec... as portainer is not supported anymore)
Then I can try myself an see if it is working that way.

**Comment by Bascht74** [comment]
The only thing is that there are two dependencies here in that file:
https://github.com/vinteo/py-opensprinkler/blob/master/setup.py

Other integrations doesn't use strict version numbers here, or ">=" instead of "==". 

e.g. HA unifi integration:
```
setup(
    install_requires=["aiohttp", "async_timeout", "orjson"],
)
```

yours:
```
setup(
    install_requires=["aiohttp==3.8.1", "backoff==1.10.0"],
)
```

backoff 1.10.0 is from december 2019 and aiohttp 3.8.1. is from november 2021. 
Maybe those verions cannot be used with HA?

**Comment by vinteo** [comment]
I tried with the latest version of backoff and it seems to have resolved it. Will do a release soon

**Comment by Bascht74** [comment]
@venteo Great to hear! 
Waiting for the new release of the integration itself that will use 0.7.4!
Then I will test and report the result in my "standard" environment...

Seb

**Comment by vinteo** [comment]
v1.1.11 has been released, thanks for your help

**Comment by vinteo** [comment]
I have pulled the released as it doesn't work with the current version lol. I will release it when 2022.11 is released
