### ISSUE TITLE
Compatibility with Home Assistant 2022.12

### ISSUE THREAD

**Issue by piio** [vinteo/py-opensprinkler#69]
Hi,
After installing beta release of Home Assistant 2022.12 pyopensprinkler is not installing automatically.
I have installed it manually, but in logs I see:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
homeassistant 2022.12.0b0 requires aiohttp==3.8.3, but you have aiohttp 3.8.1 which is incompatible.

I think that aiohttp requirements should be bumped to 3.8.3

**Comment by Bascht74** [comment]
same here.

**Comment by vinteo** [comment]
fixed in #70

**Comment by vinteo** [comment]
will do a component release once 2022.12 is released
