### ISSUE TITLE
Component won't load in 2023.7.3

### ISSUE THREAD

**Issue by collinstork** [vinteo/py-opensprinkler#77]
in 2023.7.3 home assistant bumped aiohttp to 3.8.5 now I'm getting this error:

> Unable to install package pyopensprinkler==0.7.6: ERROR: Cannot install pyopensprinkler==0.7.6 because these package versions have conflicting dependencies.

in setup.py you have: 
install_requires=["aiohttp==3.8.4", "backoff==2.2.1"]

Guessing that this just needs to be bumped here as well.

**Comment by vinteo** [comment]
fixed in 0.7.7
