### ISSUE TITLE
Water level not used when running a program

### ISSUE THREAD

**Issue by booysenn** [vinteo/py-opensprinkler#79]
Hi,

I use the [home assistant integration](https://github.com/vinteo/hass-opensprinkler) when you manually run a program it always defaults to not use the water level and runs all stations at 100% level.

This is due to the uwt flag hard coded to 0 in the [program run code](https://github.com/vinteo/py-opensprinkler/blob/2dbc5ddc29a0f6fef23a01e5b86240617a7a3427/pyopensprinkler/program.py#L42)

Changing it to ` params = {"pid": self._index, "uwt": int(self.use_weather_adjustments)}` allows it to follow what is configured in the open sprinkler program.

**Comment by vinteo** [comment]
Released in 0.7.13 https://pypi.org/project/pyopensprinkler/0.7.13/

Thank you!

**Comment by booysenn** [comment]
Thank you!
