### ISSUE TITLE
Possible to access Controller variables?

### ISSUE THREAD

**Issue by jaydeel** [vinteo/py-opensprinkler#92]
Is it possible to access the Controller's variables (API Keyword /jc)

I'd like to test if the controller is disabled before sending a station.run command.
Currently, the API (v2.3.3) ignores the disable operation setting when executing station.run.

The relevant /jc return variable appears to be 'en' (Operationenablebit).

**Comment by vinteo** [comment]
The switch that controls that variable is `switch.<contoller_name>_enabled` which by default is `switch.opensprinkler_enabled`. You can check the state of that

**Comment by jaydeel** [comment]
I've tried the following and get an error:
```
controller_is_enabled = switch.opensprinkler_enabled
NameError: name 'switch' is not defined
```
How do I define 'switch'?

**Comment by vinteo** [comment]
oh sorry i thought this was the other repo.

try 
```
controller_is_enabled = self._controller._get_variable('en')
```

**Comment by jaydeel** [comment]
Thanks. I'm a Python novice and not sure how to define 'self' in my current implementation.
Here's my code...

```
import asyncio
from aiohttp import ClientSession
from pyopensprinkler import Controller as OpenSprinklerController
async def main() -> None:
     async with ClientSession() as session:
        controller = OpenSprinklerController(OPENSPRINKLER_URL, OPENSPRINKLER_PASSWORD)
        ...

```

**Comment by vinteo** [comment]
then it should be just 

`controller.enabled`

**Comment by jaydeel** [comment]
Perfect! Thx!
